version: "3.8"

services:
  service1_v1:
    build: ./service1
    container_name: service1_v1
    environment:
      - SERVICE2_URL=http://service2_v1:8300/status
      - STORAGE_URL=http://storage:8200/log
    networks:
      - appnet
    volumes:
      - ./vstorage:/vstorage
    depends_on:
      - service2_v1
      - storage

  service2_v1:
    build: ./service2
    container_name: service2_v1
    networks:
      - appnet
    volumes:
      - ./vstorage:/vstorage
    depends_on:
      - storage

  service1_v2:
    build: ./service1
    container_name: service1_v2
    environment:
      - SERVICE2_URL=http://service2_v2:8300/status
      - STORAGE_URL=http://storage:8200/log
    networks:
      - appnet
    volumes:
      - ./vstorage:/vstorage
    depends_on:
      - service2_v2
      - storage

  service2_v2:
    build: ./service2
    container_name: service2_v2
    networks:
      - appnet
    volumes:
      - ./vstorage:/vstorage
    depends_on:
      - storage

  storage:
    build: ./storage
    container_name: storage
    ports:
      - "8200:8200"
    networks:
      - appnet
    volumes:
      - storage_data:/data

  console:
    build: ./console
    container_name: console
    ports:
      - "8198:8198"
    networks:
      - appnet
    environment:
      - CONSOLE_USER=admin
      - CONSOLE_PASS=adminpass
      - STORAGE_URL=http://storage:8200
      - SERVICE1_V1_URL=http://service1_v1:8199/status
      - SERVICE1_V2_URL=http://service1_v2:8199/status
    volumes:
      - ./vstorage:/vstorage
      - ./gateway/active.conf:/etc/nginx/conf.d/active.conf
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - service1_v1
      - service2_v1
      - storage

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "80:80"
      - "443:443"
    networks:
      - appnet
    volumes:
      - ./gateway/active.conf:/etc/nginx/conf.d/active.conf
      - ./vstorage/certs:/etc/nginx/certs:ro
    depends_on:
      - service1_v1

networks:
  appnet:
    driver: bridge

volumes:
  storage_data: